from langchain_google_genai import ChatGoogleGenecativeAI
from langchain_core.messages import HumanMessage

from my_models import GEMINI_FLASH
from my_keys import GEMINI_API_KEY
from my_helper import encode_image